#!/usr/bin/env python3
"""Render the deployable Splunk apps from the catalog.

    python -m generators.build [--validate-only]

Phase 2 renders the index app. Phases 3 and 4 add tristate_rbac and the
workspace apps to the same tree.

Nothing here is ever hand-edited: change the catalog and regenerate. The
output directory is wiped on each run so a removed catalog entry cannot leave
an orphan behind.
"""

import argparse
import hashlib
import json
import os
import shutil
import sys

from generators import loader

ROOT = loader.ROOT
BUILD_DIR = os.path.join(ROOT, "build", "apps")
INVENTORY = os.path.join(ROOT, "reports", "resolved_inventory.json")

# Sourcetype timestamp hints. Only what is known from the sample export; a
# sourcetype absent here gets the safe defaults, and every run lists the ones
# that do, so the gap stays visible.
TIME_HINTS = {
    "linux:system:messages": {"TZ": "UTC"},
    "linux:system:syslog": {"TZ": "UTC"},
    "linux:system:secure": {"TZ": "UTC"},
    "microsoft:windows:eventlog:xml": {"TZ": "UTC"},
    "microsoft:windows:eventlog:snare": {"TZ": "UTC"},
    "o365:management:activity": {"TZ": "UTC",
                                 "TIME_FORMAT": "%Y-%m-%dT%H:%M:%S"},
    "azure:aad:signin": {"TZ": "UTC", "TIME_FORMAT": "%Y-%m-%dT%H:%M:%S"},
    "oracle:oci:audit": {"TZ": "UTC", "TIME_FORMAT": "%Y-%m-%dT%H:%M:%S"},
    "vmware:esx:syslog": {"TZ": "UTC"},
}


def catalog_version(catalog):
    """A version stamped from the catalog's content hash.

    The strategy requires the app version to change on every RBAC change; a
    content hash guarantees that without anyone remembering to bump it.
    """
    digest = hashlib.sha256()
    for name in sorted(catalog.FILES):
        path = os.path.join(catalog.dir, f"{name}.yaml")
        with open(path, "rb") as handle:
            digest.update(handle.read())
    return "1.0." + digest.hexdigest()[:8]


def load_inventory():
    """Governed sourcetypes and sources per index, from the last resolve run.

    Sourcetypes are data-dependent — a mapping template such as
    `vmware:esxlog:{tail_lower}` only resolves against observed values — so
    props.conf coverage depends on having profiled an export.
    """
    if not os.path.exists(INVENTORY):
        return None
    with open(INVENTORY, encoding="utf-8") as handle:
        return json.load(handle)


def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines).rstrip() + "\n")


def render_indexes_app(catalog, inventory, version):
    """tristate_indexes — indexes.conf, props.conf, app.conf, local.meta."""
    app = os.path.join(BUILD_DIR, "tristate_indexes")
    exempt_note = {e["name"]: e.get("naming_exception")
                   for e in catalog.index_list}

    conf = [
        "# GENERATED by generators/build.py — do not edit.",
        "# Change catalog/indexes.yaml or catalog/taxonomy.yaml and rebuild.",
        "#",
        "# Deviation from the strategy's authoritative paths: on this",
        "# standalone instance indexes deploy in an app under etc/apps rather",
        "# than etc/manager-apps distributed by the cluster manager (ADR-004).",
        "#",
        "# The VM has a single storage tier, so homePath and coldPath sit on",
        "# the same volume. frozenTimePeriodInSecs encodes SEARCHABLE",
        "# retention (hot + cold); any post-frozen archive period is a",
        "# custody obligation handled outside Splunk.",
        "",
    ]
    for entry in sorted(catalog.index_list, key=lambda e: e["name"]):
        name = entry["name"]
        if name in catalog.provided:
            conf.append(f"# {name}: provided by Splunk "
                        f"({entry['provided_by']}) — governed for access only, "
                        f"not defined here.")
            conf.append("")
            continue
        tier = catalog.retention(name)
        frozen = catalog.frozen_seconds(name)
        conf.append(f"[{name}]")
        conf.append(f"# {entry['description'].strip().splitlines()[0]}")
        conf.append(f"# owners: business={entry['owner_business']} "
                    f"technical={entry['owner_technical']}")
        if exempt_note.get(name):
            conf.append(f"# naming exception: {exempt_note[name]}")
        conf.append(f"homePath   = $SPLUNK_DB/{name}/db")
        conf.append(f"coldPath   = $SPLUNK_DB/{name}/colddb")
        conf.append(f"thawedPath = $SPLUNK_DB/{name}/thaweddb")
        if frozen:
            conf.append(f"# {tier['name']}: {tier['hot_days']}d hot + "
                        f"{tier['cold_days']}d cold = "
                        f"{tier['searchable_days']}d searchable"
                        + (f", then {tier['archive_days']}d archive"
                           if tier.get("archive_days") else ""))
            conf.append(f"frozenTimePeriodInSecs = {frozen}")
        conf.append("")
    write(os.path.join(app, "local", "indexes.conf"), conf)

    props = [
        "# GENERATED by generators/build.py — do not edit.",
        "#",
        "# SHOULD_LINEMERGE=false on every sourcetype: the strategy requires",
        "# reliable event breaking, and line merging is the usual cause of",
        "# multi-event blobs. TZ is set where the source is known to log UTC;",
        "# the strategy's default assumption is UTC unless the event carries",
        "# an offset.",
        "",
    ]
    sourcetypes = set()
    if inventory:
        for record in inventory["indexes"].values():
            sourcetypes.update(record["sourcetypes"])
    for fixture in catalog.fixtures.values():
        sourcetypes.add(fixture["sourcetype"])
    untyped = []
    for sourcetype in sorted(sourcetypes):
        if sourcetype == "stash":
            continue        # vendor-mandated; Splunk defines its parsing
        props.append(f"[{sourcetype}]")
        props.append("SHOULD_LINEMERGE = false")
        hints = TIME_HINTS.get(sourcetype)
        if hints:
            for key in sorted(hints):
                props.append(f"{key} = {hints[key]}")
        else:
            untyped.append(sourcetype)
            props.append("# no timestamp hint recorded — relies on Splunk "
                         "auto-detection")
        props.append("")
    write(os.path.join(app, "local", "props.conf"), props)

    write(os.path.join(app, "default", "app.conf"), [
        "# GENERATED by generators/build.py — do not edit.",
        "[install]",
        "is_configured = true",
        "",
        "[package]",
        "id = tristate_indexes",
        "",
        "[ui]",
        "is_visible = false",
        "label = Tri-State Governed Indexes",
        "",
        "[launcher]",
        "author = Tri-State Technical Services",
        f"version = {version}",
        "description = Governed index definitions generated from the "
        "Splunk RBAC catalog.",
    ])

    write(os.path.join(app, "metadata", "local.meta"), [
        "# GENERATED by generators/build.py — do not edit.",
        "# Write access is restricted to platform administrators: the strategy",
        "# prohibits configuration changes outside the deployment app, and",
        "# this is the technical enforcement of that rule.",
        "[]",
        "access = read : [ * ], write : [ admin ]",
        "export = system",
    ])
    return len(catalog.index_list), len(sourcetypes), untyped


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--validate-only", action="store_true",
                        help="validate the catalog and exit without rendering")
    args = parser.parse_args()

    catalog = loader.Catalog()
    if catalog.errors:
        print(f"catalog has {len(catalog.errors)} errors — refusing to build:")
        for error in catalog.errors:
            print(f"  {error}")
        return 1
    print(f"catalog: {len(catalog.index_list)} indexes, validation clean")
    if args.validate_only:
        return 0

    version = catalog_version(catalog)
    inventory = load_inventory()
    if inventory is None:
        print("WARNING: no reports/resolved_inventory.json — props.conf will "
              "cover only the coverage fixtures. Run `make profile` first.")

    if os.path.exists(BUILD_DIR):
        shutil.rmtree(BUILD_DIR)
    indexes, sourcetypes, untyped = render_indexes_app(catalog, inventory,
                                                       version)

    print(f"built tristate_indexes v{version}: {indexes} indexes, "
          f"{sourcetypes} sourcetypes")
    if untyped:
        print(f"  {len(untyped)} sourcetypes have no timestamp hint and rely "
              f"on auto-detection:")
        for name in untyped[:8]:
            print(f"    {name}")
        if len(untyped) > 8:
            print(f"    ... and {len(untyped) - 8} more")
    print(f"output: {os.path.relpath(BUILD_DIR, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
