#!/usr/bin/env python3
"""Render the deployable Splunk apps from the catalog.

    python -m generators.build [--validate-only]

Phase 2 renders the index app. Phases 3 and 4 add tristate_rbac and the
workspace apps to the same tree.

Nothing here is ever hand-edited: change the catalog and regenerate. The
output directory is wiped on each run so a removed catalog entry cannot leave
an orphan behind.
"""

import argparse
import hashlib
import json
import os
import shutil
import sys

from generators import loader

ROOT = loader.ROOT
BUILD_DIR = os.path.join(ROOT, "build", "apps")
INVENTORY = os.path.join(ROOT, "reports", "resolved_inventory.json")

# Sourcetype timestamp hints. Only what is known from the sample export; a
# sourcetype absent here gets the safe defaults, and every run lists the ones
# that do, so the gap stays visible.
TIME_HINTS = {
    "linux:system:messages": {"TZ": "UTC"},
    "linux:system:syslog": {"TZ": "UTC"},
    "linux:system:secure": {"TZ": "UTC"},
    "microsoft:windows:eventlog:xml": {"TZ": "UTC"},
    "microsoft:windows:eventlog:snare": {"TZ": "UTC"},
    "o365:management:activity": {"TZ": "UTC",
                                 "TIME_FORMAT": "%Y-%m-%dT%H:%M:%S"},
    "azure:aad:signin": {"TZ": "UTC", "TIME_FORMAT": "%Y-%m-%dT%H:%M:%S"},
    "oracle:oci:audit": {"TZ": "UTC", "TIME_FORMAT": "%Y-%m-%dT%H:%M:%S"},
    "vmware:esx:syslog": {"TZ": "UTC"},
}


def catalog_version(catalog):
    """A version stamped from the catalog's content hash.

    The strategy requires the app version to change on every RBAC change; a
    content hash guarantees that without anyone remembering to bump it.
    """
    digest = hashlib.sha256()
    for name in sorted(catalog.FILES):
        path = os.path.join(catalog.dir, f"{name}.yaml")
        with open(path, "rb") as handle:
            digest.update(handle.read())
    return "1.0." + digest.hexdigest()[:8]


def load_inventory():
    """Governed sourcetypes and sources per index, from the last resolve run.

    Sourcetypes are data-dependent — a mapping template such as
    `vmware:esxlog:{tail_lower}` only resolves against observed values — so
    props.conf coverage depends on having profiled an export.
    """
    if not os.path.exists(INVENTORY):
        return None
    with open(INVENTORY, encoding="utf-8") as handle:
        return json.load(handle)


def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines).rstrip() + "\n")


def render_indexes_app(catalog, inventory, version):
    """tristate_indexes — indexes.conf, props.conf, app.conf, local.meta."""
    app = os.path.join(BUILD_DIR, "tristate_indexes")
    exempt_note = {e["name"]: e.get("naming_exception")
                   for e in catalog.index_list}

    conf = [
        "# GENERATED by generators/build.py — do not edit.",
        "# Change catalog/indexes.yaml or catalog/taxonomy.yaml and rebuild.",
        "#",
        "# Deviation from the strategy's authoritative paths: on this",
        "# standalone instance indexes deploy in an app under etc/apps rather",
        "# than etc/manager-apps distributed by the cluster manager (ADR-004).",
        "#",
        "# The VM has a single storage tier, so homePath and coldPath sit on",
        "# the same volume. frozenTimePeriodInSecs encodes SEARCHABLE",
        "# retention (hot + cold); any post-frozen archive period is a",
        "# custody obligation handled outside Splunk.",
        "",
    ]
    for entry in sorted(catalog.index_list, key=lambda e: e["name"]):
        name = entry["name"]
        if name in catalog.provided:
            conf.append(f"# {name}: provided by Splunk "
                        f"({entry['provided_by']}) — governed for access only, "
                        f"not defined here.")
            conf.append("")
            continue
        tier = catalog.retention(name)
        frozen = catalog.frozen_seconds(name)
        conf.append(f"[{name}]")
        conf.append(f"# {entry['description'].strip().splitlines()[0]}")
        conf.append(f"# owners: business={entry['owner_business']} "
                    f"technical={entry['owner_technical']}")
        if exempt_note.get(name):
            conf.append(f"# naming exception: {exempt_note[name]}")
        conf.append(f"homePath   = $SPLUNK_DB/{name}/db")
        conf.append(f"coldPath   = $SPLUNK_DB/{name}/colddb")
        conf.append(f"thawedPath = $SPLUNK_DB/{name}/thaweddb")
        if frozen:
            conf.append(f"# {tier['name']}: {tier['hot_days']}d hot + "
                        f"{tier['cold_days']}d cold = "
                        f"{tier['searchable_days']}d searchable"
                        + (f", then {tier['archive_days']}d archive"
                           if tier.get("archive_days") else ""))
            conf.append(f"frozenTimePeriodInSecs = {frozen}")
        conf.append("")
    write(os.path.join(app, "local", "indexes.conf"), conf)

    props = [
        "# GENERATED by generators/build.py — do not edit.",
        "#",
        "# SHOULD_LINEMERGE=false on every sourcetype: the strategy requires",
        "# reliable event breaking, and line merging is the usual cause of",
        "# multi-event blobs. TZ is set where the source is known to log UTC;",
        "# the strategy's default assumption is UTC unless the event carries",
        "# an offset.",
        "",
    ]
    sourcetypes = set()
    if inventory:
        for record in inventory["indexes"].values():
            sourcetypes.update(record["sourcetypes"])
    for fixture in catalog.fixtures.values():
        sourcetypes.add(fixture["sourcetype"])
    untyped = []
    for sourcetype in sorted(sourcetypes):
        if sourcetype == "stash":
            continue        # vendor-mandated; Splunk defines its parsing
        props.append(f"[{sourcetype}]")
        props.append("SHOULD_LINEMERGE = false")
        hints = TIME_HINTS.get(sourcetype)
        if hints:
            for key in sorted(hints):
                props.append(f"{key} = {hints[key]}")
        else:
            untyped.append(sourcetype)
            props.append("# no timestamp hint recorded — relies on Splunk "
                         "auto-detection")
        props.append("")
    write(os.path.join(app, "local", "props.conf"), props)

    write(os.path.join(app, "default", "app.conf"), [
        "# GENERATED by generators/build.py — do not edit.",
        "[install]",
        "is_configured = true",
        "",
        "[package]",
        "id = tristate_indexes",
        "",
        "[ui]",
        "is_visible = false",
        "label = Tri-State Governed Indexes",
        "",
        "[launcher]",
        "author = Tri-State Technical Services",
        f"version = {version}",
        "description = Governed index definitions generated from the "
        "Splunk RBAC catalog.",
    ])

    write(os.path.join(app, "metadata", "local.meta"), [
        "# GENERATED by generators/build.py — do not edit.",
        "# Write access is restricted to platform administrators: the strategy",
        "# prohibits configuration changes outside the deployment app, and",
        "# this is the technical enforcement of that rule.",
        "[]",
        "access = read : [ * ], write : [ admin ]",
        "export = system",
    ])
    return len(catalog.index_list), len(sourcetypes), untyped


def render_rbac_app(catalog, version):
    """tristate_rbac — authorize.conf, the roleMap template, and the detections."""
    app = os.path.join(BUILD_DIR, "tristate_rbac")

    conf = [
        "# GENERATED by generators/build.py — do not edit.",
        "# Change catalog/bundles.yaml or catalog/roles.yaml and rebuild.",
        "#",
        "# A pr_* stanza grants ONE kind of access. An rl_* stanza holds",
        "# importRoles and nothing else, so a Business Role carries no permission",
        "# of its own.",
        "#",
        "# No stanza imports admin, power, user, or can_delete. The strategy",
        "# forbids using a built-in role as a component; pr_feat_baseline is the",
        "# maintained substitute for the user role.",
        "",
    ]

    for bundle in catalog.bundle_groups["data"]:
        conf.append(f"[role_{bundle['name']}]")
        conf.append(f"# {' '.join(bundle['description'].split())}")
        allowed = ";".join(bundle.get("indexes_allowed", []))
        conf.append(f"srchIndexesAllowed = {allowed}")
        default = ";".join(bundle.get("indexes_default", []))
        if default:
            conf.append(f"srchIndexesDefault = {default}")
        if bundle.get("srch_filter"):
            conf.append(f"srchFilter = {bundle['srch_filter']}")
        conf.append("")

    for bundle in catalog.bundle_groups["search"]:
        conf.append(f"[role_{bundle['name']}]")
        conf.append(f"# {' '.join(bundle['description'].split())}")
        for capability in bundle.get("capabilities", []):
            conf.append(f"{capability} = enabled")
        for key, value in (bundle.get("envelope") or {}).items():
            conf.append(f"{key} = {value}")
        conf.append("")

    for bundle in catalog.bundle_groups["feat"]:
        conf.append(f"[role_{bundle['name']}]")
        conf.append(f"# {' '.join(bundle['description'].split())}")
        if bundle.get("sensitive"):
            governance = bundle.get("governance") or {}
            conf.append("# SENSITIVE TIER. Governance required by the strategy:")
            for key in sorted(governance):
                conf.append(f"#   {key}: {governance[key]}")
        for capability in bundle.get("capabilities", []):
            conf.append(f"{capability} = enabled")
        conf.append("")

    for bundle in catalog.bundle_groups["workspace"]:
        conf.append(f"[role_{bundle['name']}]")
        conf.append(f"# {' '.join(bundle['description'].split())}")
        conf.append("#")
        conf.append("# INTENTIONALLY EMPTY. This stanza grants no index, no")
        conf.append("# capability, and no quota. It is a named handle, and the")
        conf.append("# access is granted in each app's metadata/local.meta:")
        for app_name in bundle.get("apps", []):
            conf.append(f"#   {app_name}/metadata/local.meta")
        conf.append("# A workspace is a two-file construct. Both halves must")
        conf.append("# exist, or a user holds a role that reaches nothing.")
        conf.append("")

    for role in catalog.role_list:
        conf.append(f"[role_{role['name']}]")
        conf.append(f"# {' '.join(role['description'].split())}")
        if role.get("purpose") == "coverage":
            conf.append("# COVERAGE ROLE. Exists to make one model behaviour")
            conf.append("# observable. Not for a production population.")
        if role.get("sensitive"):
            conf.append("# SENSITIVE ROLE CHAIN.")
        conf.append("importRoles = " + ";".join(role["bundles"]))
        conf.append("")
    write(os.path.join(app, "local", "authorize.conf"), conf)

    template = [
        "# GENERATED by generators/build.py — do not edit.",
        "#",
        "# NOT DEPLOYED on the test instance, which has no identity provider",
        "# (ADR-003). A static test checks the shape of this file; live SAML",
        "# behaviour is untested.",
        "#",
        "# Exactly one role on the right of each line, and it is always an rl_*",
        "# Business Role. Direct assignment of a pr_* bundle to a group is",
        "# prohibited, and that rule is what enforces one role per user.",
        "",
        "[roleMap_SAML]",
    ]
    for role in catalog.role_list:
        if role.get("purpose") == "coverage":
            continue        # coverage roles have no production population
        template.append(f"GRP_splunk_{role['name']} = {role['name']}")
    write(os.path.join(app, "local", "authentication.conf.template"), template)

    detections = render_detections(catalog)
    write(os.path.join(app, "local", "savedsearches.conf"), detections)

    write(os.path.join(app, "default", "app.conf"), [
        "# GENERATED by generators/build.py — do not edit.",
        "[install]",
        "is_configured = true",
        "",
        "[package]",
        "id = tristate_rbac",
        "",
        "[ui]",
        "is_visible = false",
        "label = Tri-State RBAC",
        "",
        "[launcher]",
        "author = Tri-State Technical Services",
        f"version = {version}",
        "description = Role and privilege bundle definitions generated from "
        "the Splunk RBAC catalog.",
    ])

    write(os.path.join(app, "metadata", "local.meta"), [
        "# GENERATED by generators/build.py — do not edit.",
        "#",
        "# Write access is restricted to platform administrators. The strategy",
        "# requires this: it is the technical enforcement of the rule that RBAC",
        "# is changed only through this app, and never through Splunk Web.",
        "[]",
        "access = read : [ admin ], write : [ admin ]",
        "export = system",
    ])
    return len(catalog.bundle_by_name), len(catalog.role_list)


def capability_baseline():
    """The capability baseline, as a literal list for the detection's SPL.

    It is embedded in the search rather than shipped as a lookup. The lookup
    endpoint requires the file to be staged on the Splunk filesystem first, which
    the API deployment path cannot do (ADR-011). Embedding it also makes the
    detection self-contained: it cannot silently compare against a stale or
    missing lookup.

    Refresh it with `make capability-baseline` then `make build`, and review the
    diff before deploying — that review is the strategy's upgrade triage step.
    """
    path = os.path.join(ROOT, "reports", "capability_baseline.json")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as handle:
        return sorted(json.load(handle))


def render_detections(catalog):
    """The seven standing compliance detections from the strategy.

    Each is prefixed al_ per the strategy's entity naming standard. Each is
    scheduled, alerts when it returns anything, and carries a description saying
    what a result means — a detection whose output nobody can interpret gets
    suppressed rather than triaged.
    """
    sensitive = ", ".join(f'"{c}"' for c in sorted(catalog.sensitive_caps))
    destructive = ", ".join(f'"{c}"'
                            for c in sorted(catalog.taxonomy["destructive_capabilities"]))
    allowlist = ", ".join(
        f'"{r}"' for r in sorted(catalog.taxonomy["destructive_capability_allowlist"]))
    admin_roles = ", ".join(
        f'"{r["name"]}"' for r in catalog.role_list if r.get("sensitive"))

    searches = [
        ("al_rbac_multi_role_assignment",
         "Are any users assigned more than one rl_* Business Role?",
         "A result means the one-role-per-user convention is broken. Fix the "
         "IdP group membership, not the Splunk user.",
         '| rest /services/authentication/users '
         '| fields title roles | mvexpand roles | search roles=rl_* '
         '| stats dc(roles) as role_count values(roles) as roles by title '
         '| where role_count > 1',
         "0 6 * * *"),
        ("al_rbac_direct_bundle_assignment",
         "Is any user assigned a pr_* Privilege Bundle directly?",
         "A result means a bundle was assigned to a user or an IdP group. Only "
         "an rl_* Business Role may be assigned.",
         '| rest /services/authentication/users '
         '| fields title roles | mvexpand roles | search roles=pr_* '
         '| table title roles',
         "5 6 * * *"),
        ("al_rbac_sensitive_capability_sprawl",
         "Is a sensitive capability granted by a project role outside a "
         "pr_feat_admin_* bundle?",
         "A result means a sensitive capability was added to a routine bundle. "
         "It reads DIRECTLY assigned capabilities, so a role that inherits one "
         "through an admin bundle is not a finding. Built-in roles are excluded: "
         "the strategy governs admin under the sensitive tier and does not "
         "expect this project to change it.",
         f'| rest /services/authorization/roles '
         f'| fields title capabilities '
         f'| search (title=pr_* OR title=rl_*) AND NOT title=pr_feat_admin_* '
         f'| mvexpand capabilities | search capabilities IN ({sensitive}) '
         f'| table title capabilities',
         "10 6 * * *"),
        ("al_rbac_destructive_capability_check",
         "Does any Business Role grant a destructive capability outside the "
         "allow-list?",
         "A result means a role a USER can hold is able to destroy or rewrite "
         "data without approval. It examines rl_* Business Roles only: a "
         "pr_feat_admin_* bundle holding such a capability is the intended "
         "grant point, and a built-in role is outside this project's scope. "
         "The allow-list is in catalog/taxonomy.yaml.",
         f'| rest /services/authorization/roles '
         f'| fields title capabilities imported_capabilities '
         f'| search title=rl_* AND NOT title IN ({allowlist}) '
         f'| eval all_caps=mvappend(capabilities, imported_capabilities) '
         f'| fields title all_caps | mvexpand all_caps '
         f'| search all_caps IN ({destructive}) '
         f'| stats values(all_caps) as capabilities by title',
         "15 6 * * *"),
        ("al_rbac_configuration_drift",
         "Is any rl_* or pr_* role stanza defined outside the tristate_rbac "
         "app?",
         "A result means a role was created through Splunk Web or written to "
         "etc/system/local, which is outside version control and is not "
         "distributed to other search heads. Remove it and make the change in "
         "the catalog instead.",
         # The authorization/roles endpoint reports an EMPTY eai:acl.app for
         # every role and sharing=system, so it cannot answer this question. The
         # conf endpoint reports the owning app, which is what drift means.
         '| rest /servicesNS/-/-/configs/conf-authorize '
         '| eval app=\'eai:acl.app\' '
         '| search title=role_rl_* OR title=role_pr_* '
         '| search NOT app=tristate_rbac '
         '| table title app',
         "20 6 * * *"),
        ("al_rbac_sensitive_role_chain_membership",
         "Who currently holds a role chain that includes a sensitive bundle?",
         "Not a violation. This is the quarterly recertification evidence the "
         "sensitive tier requires, and it should be reviewed rather than "
         "cleared.",
         f'| rest /services/authentication/users '
         f'| fields title realname roles | mvexpand roles '
         f'| search roles IN ({admin_roles}) '
         f'| table title realname roles',
         "25 6 * * *"),
    ]

    baseline = capability_baseline()
    if baseline:
        literal = ",".join(baseline)
        searches.append((
            "al_rbac_capability_catalog_change",
            "Have any capabilities been added or removed since the baseline?",
            "A result means the capability catalog changed, usually after a "
            "Splunk or app upgrade. Triage each one into a pr_feat_* bundle, or "
            "record in taxonomy.yaml that no role gets it. Refresh the baseline "
            "with `make capability-baseline` and rebuild.",
            '| rest /services/authorization/capabilities '
            '| fields capabilities | mvexpand capabilities '
            '| rename capabilities as capability | eval side="live" '
            '| append [ | makeresults '
            f'| eval capability=split("{literal}", ",") '
            '| mvexpand capability | eval side="baseline" '
            '| fields capability side ] '
            '| stats values(side) as sides by capability '
            '| where mvcount(sides)=1 '
            '| eval change=if(mvindex(sides,0)=="live", "added", "removed") '
            '| table capability change',
            "30 6 * * *"))

    lines = [
        "# GENERATED by generators/build.py — do not edit.",
        "#",
        "# The seven standing compliance detections from the strategy. Prefix al_",
        "# per the entity naming standard.",
        "#",
        "# Each alerts when it returns anything. Six report a violation; one,",
        "# al_rbac_sensitive_role_chain_membership, reports evidence for the",
        "# quarterly recertification and is expected to return rows.",
        "#",
        "# The strategy is explicit that a recurring finding is a policy gap",
        "# needing a strategy revision, and not an incident to suppress.",
        "",
    ]
    for name, question, meaning, spl, schedule in searches:
        lines.append(f"[{name}]")
        lines.append(f"# Question: {question}")
        lines.append(f"# A result means: {meaning}")
        lines.append(f"search = {spl}")
        lines.append("disabled = 0")
        lines.append("enableSched = 1")
        lines.append(f"cron_schedule = {schedule}")
        lines.append("dispatch.earliest_time = -24h")
        lines.append("dispatch.latest_time = now")
        lines.append("counttype = number of events")
        lines.append("relation = greater than")
        lines.append("quantity = 0")
        lines.append("alert.severity = 3")
        lines.append("alert.suppress = 0")
        lines.append("alert_type = number of events")
        lines.append("alert_comparator = greater than")
        lines.append("alert_threshold = 0")
        lines.append("alert.track = 1")
        lines.append("")
    return lines


def render_workspace_apps(catalog, version):
    """One app per pr_workspace_* bundle.

    A workspace is a two-file construct: the empty role stanza in tristate_rbac,
    and the access grant here. Either half alone leaves a user holding a role
    that reaches nothing, or an app no role can open.
    """
    built = []
    for bundle in catalog.bundle_groups["workspace"]:
        role = bundle["name"]
        for app_name in bundle.get("apps", []):
            app = os.path.join(BUILD_DIR, app_name)
            label = " ".join(w.capitalize() for w in
                             app_name.replace("tristate_", "")
                             .replace("_workspace", "").split("_"))
            write(os.path.join(app, "default", "app.conf"), [
                "# GENERATED by generators/build.py — do not edit.",
                "[install]",
                "is_configured = true",
                "",
                "[package]",
                f"id = {app_name}",
                "",
                "[ui]",
                "is_visible = true",
                f"label = Tri-State {label}",
                "",
                "[launcher]",
                "author = Tri-State Technical Services",
                f"version = {version}",
                f"description = Workspace for the {role} privilege bundle.",
            ])
            write(os.path.join(app, "metadata", "local.meta"), [
                "# GENERATED by generators/build.py — do not edit.",
                "#",
                f"# The second half of the {role} workspace. The first half is",
                "# the empty role stanza in tristate_rbac/local/authorize.conf.",
                "#",
                "# Read access is granted to the workspace role. Write access is",
                "# restricted to the platform administrator, so a user cannot",
                "# change the workspace they are given.",
                "[]",
                f"access = read : [ {role} ], write : [ rl_platform_admin ]",
                "export = system",
                "",
                "[views]",
                f"access = read : [ {role} ], write : [ rl_platform_admin ]",
                "export = system",
            ])
            write(os.path.join(app, "default", "data", "ui", "nav",
                               "default.xml"), [
                "<nav>",
                '  <view name="workspace_home" default="true" />',
                "</nav>",
            ])
            write(os.path.join(app, "default", "data", "ui", "views",
                               "workspace_home.xml"), [
                f'<dashboard version="1.1">',
                f"  <label>Tri-State {label}</label>",
                f"  <description>Placeholder view. It exists so app",
                f"  visibility is testable: a user who holds {role} must see",
                f"  this app, and a user who does not must not.</description>",
                "  <row>",
                "    <panel>",
                f"      <title>{label} workspace</title>",
                "      <html>",
                f"        <p>Placeholder for the {role} workspace.</p>",
                "      </html>",
                "    </panel>",
                "  </row>",
                "</dashboard>",
            ])
            built.append(app_name)
    return built


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--validate-only", action="store_true",
                        help="validate the catalog and exit without rendering")
    args = parser.parse_args()

    catalog = loader.Catalog()
    if catalog.errors:
        print(f"catalog has {len(catalog.errors)} errors — refusing to build:")
        for error in catalog.errors:
            print(f"  {error}")
        return 1
    print(f"catalog: {len(catalog.index_list)} indexes, validation clean")
    if args.validate_only:
        return 0

    version = catalog_version(catalog)
    inventory = load_inventory()
    if inventory is None:
        print("WARNING: no reports/resolved_inventory.json — props.conf will "
              "cover only the coverage fixtures. Run `make profile` first.")

    if os.path.exists(BUILD_DIR):
        shutil.rmtree(BUILD_DIR)
    indexes, sourcetypes, untyped = render_indexes_app(catalog, inventory,
                                                       version)
    bundles, roles = render_rbac_app(catalog, version)
    workspaces = render_workspace_apps(catalog, version)

    print(f"built tristate_indexes v{version}: {indexes} indexes, "
          f"{sourcetypes} sourcetypes")
    print(f"built tristate_rbac v{version}: {bundles} bundles, {roles} roles, "
          f"7 detections")
    print(f"built {len(workspaces)} workspace apps: {', '.join(workspaces)}")
    if untyped:
        print(f"  {len(untyped)} sourcetypes have no timestamp hint and rely "
              f"on auto-detection:")
        for name in untyped[:8]:
            print(f"    {name}")
        if len(untyped) > 8:
            print(f"    ... and {len(untyped) - 8} more")
    print(f"output: {os.path.relpath(BUILD_DIR, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
